/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void RestaurantConstructor(){
        Restaurant2 test =new Restaurant2("test Restaurant","$$$$$");
        assertEquals(test.getName(),"test Restaurant");
    }
    @Test void toStringRestaurant(){
        Restaurant2 test =new Restaurant2("test Restaurant","$$$$$");
        assertEquals(test.toString(),"Restaurant => { name = test Restaurant , star=0}");
    }
    @Test void reviewConstructor(){
        Review2 test =new Review2("i love testing","mohammad",2);
        assertEquals(test.getAuthor(),"mohammad");
    }
    @Test void toStringReview(){
        Review2 test =new Review2("i love testing","mohammad",2);
        assertEquals(test.toString(),"Review2{" +
                "body='" + "i love testing" + '\'' +
                ", author='" + "mohammad" + '\'' +
                ", reviewStar =" + 2 +
                '}');
    }
    @Test void toStringReviewAfterNewReview(){
        Restaurant2 test =new Restaurant2("test Restaurant","$$$$$");
        test.addReview("i love testing","mohammad",1);
        assertEquals(test.toString(),"Restaurant2 => {name = test Restaurant', star=1.0}\n" +
                " category='$$$$$" +
                "\n" +
                " Reviews={ body => i love testing | author => mohammad | Review Star =>1.0 || }");
    }
    @Test void associationReviewAfterNewReviewBetweenReviewAndRestaurantCon(){
        Restaurant2 test =new Restaurant2("Restaurant 1","$$$$$");

        test.addReview("i love testing","mohammad",1);

        Restaurant2 test2 =new Restaurant2("test Restaurant 2","$$$$$");
        test2.addReview("i love testing","mohammad",5);

        assertEquals(test.toString(),"Restaurant2 => {name = Restaurant 1', star=1.0}\n" +
                " category='$$$$$" +
                "\n" +
                " Reviews={ body => i love testing | author => mohammad | Review Star =>1.0 || }");

        assertEquals(test2.toString(),"Restaurant2 => {name = test Restaurant 2', star=5.0}\n" +
                " category='$$$$$" +
                "\n" +
                " Reviews={ body => i love testing | author => mohammad | Review Star =>5.0 || }");
    }
    @Test void checkIfTheNumberOfStarsChange(){
        Restaurant2 test =new Restaurant2("test Restaurant","$$$$$");
        test.addReview("i love testing","mohammad",1);
        test.addReview("i love testing","mohammad",3);
        test.addReview("i love testing","mohammad",5);
        test.setStar(test.getReviewStar());
        assertEquals(test.getStar1(),1.0);
    }

}
