/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.stream.JsonReader;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;


public class App {

    public static void main(String[] args) throws IOException {
        String  path = "./app/src/main/resources/recentquotes.json";
        readJson(path);

    }
    public static Boolean readJson(String path){
        try{
            Gson gson = new Gson();

            JsonReader jsonReader =new JsonReader(new BufferedReader(new FileReader(path)));

            ArrayList<String> author = new ArrayList<>();
            ArrayList<String> text = new ArrayList<>();

            jsonReader.beginArray();
            while (jsonReader.hasNext()) {
                Quotes obj2 = gson.fromJson(jsonReader, Quotes.class);

                author.add(obj2.getAuthor());
                text.add(obj2.getText());
            }
            jsonReader.endArray();

//            System.out.println(author.size());
//            System.out.println(text.size());
            int random = (int) Math.floor(Math.random()*author.size());

            System.out.println("author :" +author.get(random) +"\n"+ "quote : " +text.get(random));
                return true;
        }catch (IOException e){
            System.out.println("error");
            return false;
        }

    }
}
