/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testThePath() {
        String  worngPath = "./app/src/main/resources/recentquotes.json";
//        App.readJson(worngPath);
        assertEquals(App.readJson(worngPath),false);
    }
}
