/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance2;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {

        Restaurant restaurant = new Restaurant("falafel restaurant","$$$$$");
//        Restaurant restaurant2 = new Restaurant("mmm restaurant","$$");

//        restaurant2.addCategory("mmm","12$");

        restaurant.addCategory("tomato ","5$ ");
        restaurant.addCategory("potato ","50$ ");
        restaurant.addCategory("falafel ","500$ ");


        restaurant.addReview("I love the falafel222","mohammad33",5);
        restaurant.addReview("I love the falafel","mohammad",4);
        restaurant.addReview("I love the 11111111","mohammad33",5);
        restaurant.addReview("I love the 22222222","mohammad",8);

        Shop shop =new Shop("mohammad shop","sells computer parts","$$$");
        shop.addReview("the prices was good ","mohammad jaradat",1);
        shop.addReview("the prices was good  22 ","mohammad jaradat22",5);
        System.out.println(shop);
        System.out.println("------------------**");


        ArrayList<String> movie =new ArrayList<>();

        Theater theater =new Theater("The old Theater",movie);
        theater.addNewMovie("fly1");
        theater.addNewMovie("fly2");
        theater.addNewMovie("fly3");
//        System.out.println(theater.getMovies());
        theater.addReview("fly2","I love fly2 movie","mohammad jaradat 1",10);
        theater.addReview("fly3","The fly3 movie its ok","mohammad jaradat 2",8);
        System.out.println(theater);
        System.out.println("------------------**");


//
        System.out.println(restaurant);
        System.out.println("\n ***** The new restaurant stars : "+ restaurant.getStar1()+" ******");
//        System.out.println(restaurant2);
//        System.out.println("\n ***** The new restaurant stars : "+ restaurant2.getStar1()+" ******");
    }

}
