/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance2;

public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        System.out.println("hello");
        Restaurant2 restaurant2 = new Restaurant2("falafel restaurant","$$$$$");

//        restaurant2.addCategory("tomato ","5$ ");
//        restaurant2.addCategory("potato ","50$ ");
//        restaurant2.addCategory("falafel ","500$ ");


        restaurant2.addReview("I love the falafel222","mohammad33",5);
        restaurant2.addReview("I love the falafel","mohammad",4);
        restaurant2.addReview("I love the falafel222","mohammad33",5);
        restaurant2.addReview("I love the falafel","mohammad",8);

        System.out.println(restaurant2);
        System.out.println("\n ***** The new restaurant2 stars : "+ restaurant2.getStar1()+" ******");
    }

}
